---
properties:
  - name: ESPACE
    value: ${PROD_SPACE_NAME}
    type: text
  - name: PAYS
    value: 'de'
    type: text
stages:
- name: Build & cloudant
#  inputs:
#  - type: git
#    branch: ${PROD_SPACE_NAME}
#    service: ${REPO}
#  triggers:
#  - type: commit
  jobs:
  - name: Génération
    type: shell
    script: |
      #!/bin/bash

      git clone https://oauth2:xxxxxxxxxxxx@git.eu-de.bluemix.net/ezyfront-deploiement/application.git
      git clone https://oauth2:xxxxxxxxxxxx@git.eu-de.bluemix.net/ezyfront-deploiement/configuration.git

      chmod 777 application/*.sh

      application/deploie_application.sh build --espace ${ESPACE} --pays ${PAYS}
  - name: MAJ cloudant
      type: shell
      script: |
        #!/bin/bash

        git clone https://oauth2:xxxxxxxxxxxx@git.eu-de.bluemix.net/ezyfront-deploiement/application.git
        git clone https://oauth2:xxxxxxxxxxxx@git.eu-de.bluemix.net/ezyfront-deploiement/configuration.git

        chmod 777 application/*.sh

        application/deploie_application.sh cloudant  --espace ${ESPACE} --pays ${PAYS}
- name: Déploiement
  inputs:
  - type: job
    stage: "Build & cloudant"
    job: Génération
  triggers:
  - type: stage
#  properties:
#  - name: CF_APP_NAME
#    value: ${ESPACE}
#    type: text
  jobs:
  - name: "Déployement"
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
        #!/bin/bash
        git clone https://oauth2:xxxxxxxxxxxx@git.eu-de.bluemix.net/ezyfront-deploiement/application.git
        git clone https://oauth2:xxxxxxxxxxxx@git.eu-de.bluemix.net/ezyfront-deploiement/configuration.git

        chmod 777 application/*.sh

        application/deploie_application.sh deploy --espace ${ESPACE} --pays ${PAYS}
  - name: Test
    type: tester
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
        #!/bin/bash
        git clone https://oauth2:xxxxxxxxxxxx@git.eu-de.bluemix.net/ezyfront-deploiement/application.git
        git clone https://oauth2:xxxxxxxxxxxx@git.eu-de.bluemix.net/ezyfront-deploiement/configuration.git

        chmod 777 application/*.sh

        application/deploie_application.sh test --espace ${ESPACE} --pays ${PAYS}
