---
stages:
- name: Build & cloudant
  inputs:
  - type: git
    branch: ${PROD_SPACE_NAME}
    service: ${SAMPLE_REPO}
  triggers:
  - type: commit
  jobs:
  - name: Génération
    type: shell
    script: |
      #!/bin/bash

      git clone https://oauth2:xxxxxxxxxxxx@git.eu-de.bluemix.net/ezyfront-deploiement/application.git
      git clone https://oauth2:xxxxxxxxxxxx@git.eu-de.bluemix.net/ezyfront-deploiement/configuration.git

      chmod 777 application/*.sh

      application/deploie_application.sh build --espace ${PROD_SPACE_NAME} --pays de
  - name: MAJ cloudant
      type: shell
      script: |
        #!/bin/bash

        git clone https://oauth2:xxxxxxxxxxxx@git.eu-de.bluemix.net/ezyfront-deploiement/application.git
        git clone https://oauth2:xxxxxxxxxxxx@git.eu-de.bluemix.net/ezyfront-deploiement/configuration.git

        chmod 777 application/*.sh

        application/deploie_application.sh cloudant  --espace ${PROD_SPACE_NAME} --pays de
- name: Déploiement
  inputs:
  - type: job
    stage: Build & cloudant
    job: Génération
  triggers:
  - type: stage
  properties:
  - name: CF_APP_NAME
    value: ${PROD_SPACE_NAME}
    type: text
  jobs:
  - name: Rolling Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
      api_key: ${API_KEY}
    script: |
        #!/bin/bash
        git clone https://oauth2:xxxxxxxxxxxx@git.eu-de.bluemix.net/ezyfront-deploiement/application.git
        git clone https://oauth2:xxxxxxxxxxxx@git.eu-de.bluemix.net/ezyfront-deploiement/configuration.git

        chmod 777 application/*.sh

        application/deploie_application.sh deploy --espace ${PROD_SPACE_NAME} --pays de
  - name: Test
    type: tester
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
      api_key: ${API_KEY}
    script: |
        #!/bin/bash
        git clone https://oauth2:xxxxxxxxxxxx@git.eu-de.bluemix.net/ezyfront-deploiement/application.git
        git clone https://oauth2:xxxxxxxxxxxx@git.eu-de.bluemix.net/ezyfront-deploiement/configuration.git

        chmod 777 application/*.sh

        application/deploie_application.sh test --espace ${PROD_SPACE_NAME} --pays de
