version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  header: '![](toolchain.svg)'
  icon: icon.svg
  required:
    - repo
    - build
  info:
    git url: >-
      [https://github.com/marvin-ezyfront/ezyfront-toolchain](https://github.com/marvin-ezyfront/ezyfront-toolchain)
toolchain:
  name: 'generic-api-ardoise'
  template:
    getting_started:
      $ref: '#/messages/template.getting_started'
services:
  repo:
    service_id: hostedgit
    parameters:
      repo_name: '{{toolchain.name}}'
      repo_url: 'https://git.eu-de.bluemix.net/ezyfront/{{services.repo.parameters.repo_name}}'
      type: link
      has_issues: true
      enable_traceability: false
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{services.repo.parameters.repo_name}}'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          REPO: repo
          CF_APP_NAME: '{{form.pipeline.parameters.prod-app-name}}'
#          PROD_PAYS: '{{form.pipeline.parameters.prod-pays}}'
          PROD_SPACE_NAME: '{{form.pipeline.parameters.prod-space}}'
          PROD_ORG_NAME: '{{form.pipeline.parameters.prod-organization}}'
          PROD_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
        execute: true
form:
  pipeline:
    parameters:
      prod-app-name: '{{services.repo.parameters.repo_name}}'
      prod-region: 'eu-de'
      prod-organization: 'EZYFRONT_'
      prod-space: 'integration'
    schema:
      $ref: deploy.json
