version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  header: '![](toolchain.svg)'
  icon: icon.svg
  required:
    - repo
    - build
  info:
    git url: >-
      [https://github.com/marvin-ezyfront/ezyfront-toolchain](https://github.com/marvin-ezyfront/ezyfront-toolchain)
toolchain:
  name: '{{baseName}}-{{timestamp}}'
  template:
    getting_started:
      $ref: '#/messages/toolchain.getting_started'
services:
  repo:
    service_id: hostedgit
    parameters:
      repo_name: '{{toolchain.name}}'
      repo_url: 'https://git.eu-de.bluemix.net/ezyfront/{{toolchain.name}}'
      type: link
      has_issues: true
      enable_traceability: false
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{toolchain.name}}'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          REPO: repo
          BRANCH: '{{branch}}'
          CF_APP: '{{form.pipeline.parameters.app-name}}'
          PROD_SPACE_NAME: '{{form.pipeline.parameters.space}}'
          PROD_ORG_NAME: '{{form.pipeline.parameters.organization}}'
          PROD_REGION_ID: '{{form.pipeline.parameters.region}}'
        execute: true
form:
  pipeline:
    parameters:
      region: 'eu-de'
      organization: 'EZYFRONT_'
      space: ''
      app-name: '{{services.repo.parameters.repo_name}}'
    schema:
      $ref: deploy.json
